title = "Neuroanatomy and Behaviour"
baseURL = "https://nab.epistemehealth.com/"
languageCode = "en-US"
theme = "health-science-journal"

# The site's parameters
[params]
  home = "Home"
  abbreviatedTitle = "Neuroanat. Behav."
  description = "Neuroanatomy and Behaviour is a free open access journal for peer-reviewed behavioural neuroscience research. It is published by Episteme Health Inc., a non-profit scientific association dedicated to providing free open access publishing for medical research."
  favicon = "img/favicon.png"
  mirrorfor = "https://epistemehealth.com/index.php/nab"
  eISSN = "2652-1768"
  printISSN = ""
  
  ## Publisher Information
  publisher = {name = "Episteme Health Inc.", city = "Melbourne", state = "Victoria", country = "Australia"}
  journalDOI = "10.35430/nab"
  publisherjournalabbreviation = "NAB"
  subjects = ["Biological Sciences", "Neurosciences"]
  crossmark_enabled = true
  
  ## Homepage image. Different sizes can be used to provide responsiveness.
  homepageimageset = [{img = "img/homepage_480w.jpg", width = "480w", maxwidth = "800px"},
    {img = "img/homepage_960w.jpg", width = "960w", maxwidth = "1440px"},
    {img = "img/homepage_1920w.jpg", width = "1920w", maxwidth = ""}]
  homepageimagefallback = "img/homepage_960w.jpg"
  homepageimagealt = "Neurons artwork homepage image. CC0 Geralt/Pixabay id-582054"
  
  lenslogo = "img/lens-journal-logo.png"
  
  ## Set current issue or leave blank and the most recent issue will be used.
  currentissuepath = ""
  
  twittercard = "summary_large_image"
  twitterhandle = "@epistemehealth"
  socialimage = "img/twittercard.jpg"
  socialimagealt = "Neuroanatomy and Behaviour Logo"
  socialdescription = "Neuroanatomy and Behaviour provides free open access publishing for neuroscience."
  
  ## Set to true to load libraries from Cloudflare and Bootstrap CDNs where available. Otherwise leave blank.
  useCDN = true
  
  ## Custom blocks for the footer
  customblocks = [{ name = "Non-Profit Publishing", content = "[Episteme Health Inc.](https://about.epistemehealth.com) (Registration No. A0105005T, VIC, Australia) is a non-profit no-fee open access publisher run by scientists. All articles can be published and read without paying any fees."},
  {name = "Copyright", content = "Articles in this journal are licensed according to the author's choice of a Creative Commons Attribution or Attribution-NonCommercial license. [![Creative Commons Attribution License Logo](/img/cc-by88x31.png)](https://creativecommons.org/licenses/by/4.0/) or [![Creative Commons Attribution-NonCommercial License Logo](/img/cc-by-nc-88x31.png)](https://creativecommons.org/licenses/by-nc/4.0/)"},
  {name = "Privacy Notice", content = "No user information is collected from the static version of the *Neuroanatomy and Behaviour* website, apart from log files generated by [DNS](https://cloudflare.com) and [hosting providers](https://www.netlify.com/privacy/)."},
  {name = "Contact Us", content = "For more information contact: [Shaun Khoo](mailto:shaun.khoo@umontreal.ca) or connect with us on [Twitter](https://twitter.com/epistemehealth)."}]
  
  footercontent = "[![Crossref Member Logo](/img/crossref-badge.png)](https://crossref.org) [![OpenAIRE logo](/img/openAIRE-valid-icon.png)](https://openaire.eu)"
  
  
  [privacy]
  [privacy.googleAnalytics]
    disable = true
  [privacy.disqus]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
  
  [menu]

    [[menu.main]]
      weight = 2
      name = "Articles"
      url = "/current"
    [[menu.main]]
      weight = 3
      name = "Archives"
      url = "/article"
    [[menu.main]]
      weight = 4
      name = "Submit"
      url = "https://www.epistemehealth.com/index.php/nab/about/submissions"
    [[menu.main]]
      weight = 5
      name = "About"
      hasChildren = true
    [[menu.main]]
      parent = "About"
      name = "About the Journal"
      url = "/about/journal"
      weight = 6
    [[menu.main]]
      parent = "About"
      name = "Editorial Team"
      url = "/about/editorialTeam"
      weight = 7
    [[menu.main]]
      parent = "About"
      name = "Policies and Plan S"
      url = "https://about.epistemehealth.com/policy/"
      weight = 8
    [[menu.main]]
      parent = "About"
      name = "Volunteer"
      url = "/about/volunteer"
      weight = 9
    [[menu.main]]
      parent = "About"
      name = "Contact"
      url = "/contact"
      weight = 10

# Output formats
[mediaTypes]
  [mediaTypes."text/ris"]
    suffixes = ["ris"]
  [mediaTypes."text/bib"]
    suffixes = ["bib"]
  [mediaTypes."text/enw"]
    suffixes = ["enw"]
  [mediaTypes."text/latex"]
    suffixes = ["tex"]
    
[outputFormats]
  [outputFormats.galleyPDF]
    baseName = "view-pdf"
    isPlainText = true
    mediaType = "text/html"
    path = ""
  [outputFormats.galleyXML]
    baseName = "view-lens"
    isPlainText = true
    mediaType = "text/html"
    path = ""
  [outputFormats.galleyHTML]
    baseName = "view-html"
    isPlainText = true
    mediaType = "text/html"
    path = ""
  [outputFormats.galleyAMP]
    baseName = "view-mobile"
    isPlainText = true
    mediaType = "text/html"
    path = ""
  [outputFormats.customlens]
    baseName = "js/customlens"
    isPlainText = true
    mediaType = "application/javascript"
    path = ""
  [outputFormats.localfonts]
    baseName = "css/localfonts"
    isPlainText = true
    mediaType = "text/css"
    path = ""
  [outputFormats.lensfonts]
    baseName = "css/lensfonts"
    isPlainText = true
    mediaType = "text/css"
    path = ""
  [outputFormats.exportris]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "text/ris"
    path = ""
  [outputFormats.exportbib]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "text/bib"
    path = ""
  [outputFormats.exportenw]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "text/enw"
    path = ""
  [outputFormats.exportcsljson]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "application/json"
    path = ""
  [outputFormats.productiontex]
    baseName = "production"
    isPlainText = true
    mediaType = "text/latex"
    path = ""
  [outputFormats.productionjats]
    baseName = "production"
    isPlainText = true
    mediaType = "application/xml"
    path = ""
    
    
[outputs]
  home = ["HTML", "customlens", "localfonts", "lensfonts"]
  page = ["html", "galleyPDF", "galleyXML", "exportris", "exportenw", "exportbib", "exportcsljson" ]
  
[minify]
  disableHTML = true
  
[taxonomies]
  keyword = "keywords"